language: python
sudo: required
python:
    - "2.7"
env: PGVERSION=9.1
install:
    # - bash bin/travis-build.bash
    # Installing CKAN errors out; skip for now
    - pip install coveralls
    - pip install flake8
script:
    # - sh bin/travis-run.sh
    # Installing CKAN errors out; skip for now
    - flake8
after_success:
    - coveralls
