language: python
sudo: required
python:
    - "2.7"
env: PGVERSION=9.1
install:
    - bash bin/travis-build.bash
    - pip install coveralls
    - pip install flake8
script:
    - sh bin/travis-run.sh
    - flake8
after_success:
    - coveralls
